# Generated by Django 4.2 on 2023-12-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_post_liked_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='review',
            name='saved',
        ),
    ]
