# Generated by Django 4.2 on 2023-12-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_remove_review_description_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment_title',
        ),
    ]
