# Generated by Django 4.2 on 2023-12-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_remove_review_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True),
        ),
    ]
