# Generated by Django 4.2 on 2023-12-08 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0007_report_reportreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='world.post')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='world.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
