# Generated by Django 4.2 on 2023-12-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_reportpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.post'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.report'),
        ),
        migrations.AlterField(
            model_name='reportreview',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.report'),
        ),
        migrations.AlterField(
            model_name='reportreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.review'),
        ),
    ]
